---
title: Voeg tekst en variabelen samen in Scratch
hero_image: images/banner.png
description: Voeg tekst en variabelen samen in Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Voeg tekst en variabelen samen in Scratch
