title: scratch3-join-text
hero_image: images/banner.png
description: scratch3-join-text description
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
