title:  Join text and variables in Scratch
hero_image: images/banner.png
description:  Join text and variables in Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title:  Join text and variables in Scratch
