---
title: Cysylltu testun â newidynnau yn Scratch
hero_image: images/banner.png
description: Cysylltu testun â newidynnau yn Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Cysylltu testun â newidynnau yn Scratch
