---
title: Unir texto y variables en Scratch
hero_image: images/banner.png
description: Unir texto y variables en Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Unir texto y variables en Scratch
