---
title: Połącz tekst i zmienne w Scratch
hero_image: images/banner.png
description: Połącz tekst i zmienne w Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - title: Połącz tekst i zmienne w Scratch
