---
title: Joindre du texte et des variables dans Scratch
hero_image: images/banner.png
description: Joindre du texte et des variables dans Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Joindre du texte et des variables dans Scratch
