---
title: Unire testo e variabili in Scratch
hero_image: images/banner.png
description: Unire testo e variabili in Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-05-12"
steps:
  - 
    title: Unire testo e variabili in Scratch
